# Generated by Django 5.2.2 on 2025-06-10 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vps_rental", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("processor", models.CharField(max_length=100)),
                ("ram", models.CharField(max_length=100)),
                ("disk", models.CharField(max_length=100)),
                ("internet_speed", models.CharField(max_length=100)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="vps_rental.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика услуги",
                "verbose_name_plural": "Характеристики услуг",
                "ordering": ["id"],
            },
        ),
    ]
