# Generated by Django 5.2.2 on 2025-06-15 17:49

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vps_rental", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="mybucket"
                ),
                upload_to="",
                verbose_name="Object Upload",
            ),
        ),
    ]
