# Generated by Django 5.2.2 on 2025-06-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vps_rental", "0003_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="vps_rental.application",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="vps_rental.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга в заявке",
                "verbose_name_plural": "Услуги в заявках",
                "unique_together": {("application", "service")},
            },
        ),
    ]
