# Generated by Django 5.2.1 on 2025-05-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_applicationstatus_application_servicespecification_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
