# Generated by Django 5.2.1 on 2025-05-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_update_at_application_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.URLField(max_length=1024),
        ),
    ]
