# Generated by Django 5.2.1 on 2025-05-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.URLField(max_length=1024),
        ),
    ]
